import Assesment from "@/components/Ui/svg/assesment";
import Assignment from "@/components/Ui/svg/assignment";
import CaseStudy from "@/components/Ui/svg/caseStudy";
import Live from "@/components/Ui/svg/live";
import type { CurriculumProps } from "@/types/curriculum";

export const curriculumData: CurriculumProps = {
  heading: "Latest Curriculum Reviewed by Industry Leaders",
  description:
    "Cutting-edge digital marketing syllabus—designed by Expert trainers and endorsed by top recruiters and domain experts.",
  learningMode: "Online",
  batchTimings: [
    {
      label: "Online (Certification)",
      slots: [
        "07:30 AM to 09:30 AM",
        "10:30 AM to 12:30 PM",
        "09:00 PM to 10:30 PM",
      ],
    },
    {
      label: "",
      slots: [],
    },
  ],
  modules: [
    {
      number: 1,
      title: "Foundation of Influencer Marketing",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Introduction to Influencer Ecosystem (Instagram & YouTube)",
        "Evolution & Trends in the Creator Economy",
        "Instagram vs. YouTube – Understanding the Platforms",
        "Types of Influencers: Nano, Micro, Macro, Celeb",
        "Branding Basics: Niche, Voice, Value Proposition",
        "Audience Behavior & Follower Psychology",
        "Introduction to Content Formats: Reels, Shorts, Long-form",
        "Importance of Consistency and Content Cadence",
        "Goal Setting: Fame, Followers or Finances?",
      ],
    },
    {
      number: 2,
      title: "Instagram Mastery & Personal Branding",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Creating a Business/Creator Account on Instagram",
        "Optimizing Instagram Bio & Profile for Growth",
        "Hashtag Strategy & AI Tools for Trend Discovery",
        "Instagram SEO & Engagement Algorithms",
        "Mastering Reels: Hooks, Scripts, Transitions",
        "Carousel, Story & Live Content Best Practices",
        "Collaboration & Influencer Tagging Strategy",
        "Instagram Insights, Analytics & Growth Hacks",
        "Shadowban Prevention & Algorithm Compliance",
      ],
    },
    {
      number: 3,
      title: "YouTube Channel Creation & Optimization",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Creating & Verifying a YouTube Channel",
        "Niche Selection & Audience Mapping",
        "Channel Art, Logo, & Branding Setup",
        "SEO - Optimized Titles, Tags & Descriptions",
        "Scriptwriting & Storyboarding Techniques",
        "YouTube Shorts vs. Long - form Content Strategy",
        "Thumbnail Designing using Canva & AI Tools",
        "Community Tab & Playlist Organization",
        "Setting Up Monetization (YouTube Partner Program)",
      ],
    },
    {
      number: 4,
      title: "Content Creation Tools & Video Production",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Using Canva AI, CapCut, VN & InShot for Video Editing",
        "Mobile vs. DSLR Shooting – Framing & Lighting Basics",
        "Audio Tools, Voiceover & Background Music Integration",
        "Scriptwriting Prompts with ChatGPT & Jasper",
        "AI Voiceovers & Avatar Tools (Lumen5, HeyGen)",
        "Batch Recording & Content Calendar Planning",
        "Captions & Subtitles Tools (Veed, SubtitleBee)",
        "Planning Product/Brand Shoots",
        "Creating a Signature Visual Style",
      ],
    },
    {
      number: 5,
      title: "Influencer Campaign Strategy & Collaboration",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "How to Attract Brand Collaborations",
        "Crafting a Media Kit & Influencer Portfolio",
        "Pricing Models: Barter, Paid, Affiliate, Sponsorships",
        "Outreach Strategy to Brands & PR Agencies",
        "Influencer Platforms (Grapevine, Upfluence, Winkl, One Impression)",
        "Affiliate Marketing for Influencers",
        "FTC Guidelines, Brand Safety & Disclosure Rules",
        "Case Studies: Successful Campaign Breakdowns",
        "Negotiation & Contract Handling for Creators",
      ],
    },
    {
      number: 6,
      title: "Growth Hacking & Platform Algorithms",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Understanding Instagram & YouTube Algorithms",
        "Content Velocity vs. Quality Balance",
        "Engagement Loops: CTA, Comments & Polls",
        "Timing & Scheduling for Maximum Reach",
        "Viral Content Frameworks & Hooks",
        "Using AI Tools for Trend Forecasting",
        "Subscriber & Follower Retention Tactics",
        "Shadowban/Myth Busting & Penalty Recovery",
        "Growth Challenges, Giveaways & Cross-Promotion",
      ],
    },
    {
      number: 7,
      title: "Monetization & Revenue Strategies",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "YouTube Partner Program: Ads, Super Chats, Subscriptions",
        "Instagram Monetization: Bonuses, Collab Posts, Badges",
        "Merchandising & Dropshipping as a Creator",
        "Paid Workshops, Courses, Webinars",
        "Building a Paid Community on WhatsApp/Telegram",
        "Monetizing with Affiliate Programs & UGC Platforms",
        "Platform - Specific Monetization Policies",
        "Revenue Diversification for Long – Term Success",
        "Tracking Earnings & Creator Taxes",
      ],
    },
    {
      number: 8,
      title: "Personal Branding, Soft Skills & On-Camera Presence",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Enhancing On - Camera Confidence",
        "Public Speaking Techniques for Creators",
        "Storytelling for Personal Branding",
        "Handling Online Criticism & Trolling",
        "Body Language & Presentation Skills",
        "Personal Productivity & Creator Burnout Management",
        "Client/Brand Communication Etiquette",
        "Personal Branding via LinkedIn & Social Syncing",
        "Collaboration with Other Creators (Reels, Shorts, Lives)",
      ],
    },
  ],
};
