import Live from "@/components/Ui/svg/live";
import type { SpecialisationProps } from "@/types/specialisation";

export const specialisationData: SpecialisationProps = {
  specialisationHeading: "Fastrack Your AI Digital Marketing Career",
  specialisationDescription:
    "Learn 4 distinct specializations with a 6-month postgraduate Certification program",

  specialisationmodulesData: [
    {
      number: 1,
      title: "SEO & AI",
      badges: [
        { icon: <Live />, label: "Live Projects" },
        { icon: <Live />, label: "Interview Q&A + Placement Training" },
        { icon: <Live />, label: "Final Test on SEO & AI" },
      ],
      topics: [
        "Bing Webmaster",
        "App Store SEO",
        "SEO Audit Checklists",
        "SEO Monetization Strategies",
        "Conversion Rate Optimisation",
        "Technical SEO and Schema Algorithm Validation",
        "Optimizing AMP and Mobile Apps for PWAs",
        "How to use Generative AI & ChatGPT for SEO",
        "Advanced AI Tools For Improving Rankings",
        "Strategies for International SEO",
        "Advanced Competitor Backlink Analysis and Strategy",
        "Calculating ROI of an SEO campaign",
        "SEO Forecasting and Predictions",
        "SEO Friendly AI Blog Writing",
        "Latest Google Algorithm Updates",
        "Advanced link building strategies and Digital PR",
        "Working on the Live Projects",
        "Interview Q & A - Placements Training",
        "Final Test on SEO & AI",
      ],
    },
    {
      number: 2,
      title: "Performance Marketing & Ad Copy Writing",
      badges: [
        { icon: <Live />, label: "Live Campaigns" },
        { icon: <Live />, label: "Interview Q&A + Placement Training" },
        { icon: <Live />, label: "Final Test on Performance Marketing" },
      ],
      topics: [
        "Conversion Rate Optimisation",
        "Goals Setting + A3R3 Funnels + 4 Pillars of Performance Marketing",
        "1st Pillar Audience Definition, Creation & Evaluation",
        "In-depth study of creativity and fundamentals in advertising",
        "Ad Copy writing based on the framework and Using AI",
        "Principles of reporting and evaluating the destination of your ads",
        "Running A/B tests on Google Ads and Facebook Ads for improved outcomes",
        "Remarketing campaign setup on Google Ads and Facebook Ads",
        "Working on the Additional Setups Catalogs & Tracking",
        "Advanced ad content and creative tracking",
        "Managing live campaigns for product and service businesses",
        "Media Buying & Planning",
        "LinkedIn Paid Campaigns",
        "Quora Ads",
        "Programmatic Ads",
        "Run Paid Campaigns in Google Ads, Facebook, & Instagram",
        "Interview Q & A - Placements Training",
        "Final Test on Performance Marketing",
      ],
    },
    {
      number: 3,
      title: "Marketing Automation and MarTech",
      badges: [],
      topics: [
        "What is Project & Project Management?",
        "Managing Projects & Using Automations",
        "Improving Productivity With Automations",
        "Building ICP For B2B Businesses",
        "Data Lead Marketing & ABM Strategies",
        "Account Based Marketing - ABM",
        "Tools for Automate Outreach",
        "All About CRM",
        "Building Automations To Nurture Leads",
        "Key Metrics & Reporting Methods",
        "Email Marketing",
        "Omnichannel & Drip Email Automations",
        "Understanding Zapier ecosystem",
        "Understanding Live Chat & Chat Bot",
        "What is Chatbot Workflow",
        "Whatsapp & SMS Marketing",
        "Affiliate Marketing",
        "Google Ad Sense",
        "Building GTM (Go To Market) Strategies",
        "Mastering PLG (Product Led Growth)",
      ],
    },
    {
      number: 4,
      title: "Ecommerce Marketing Specialisation",
      badges: [{ icon: <Live />, label: "E-commerce Project" }],
      topics: [
        "Introduction to E-commerce",
        "E-commerce Business Models",
        "Choosing the Right E-commerce Platform",
        "On-Page SEO For E-commerce",
        "Off-Page SEO For E-commerce",
        "Google Ads for E-commerce",
        "Social Media Advertising For E-commerce",
        "Google Analytics for E-commerce",
        "Data Analysis & Reporting",
        "Providing Excellent Customer Service",
        "Customer Retention Strategies",
        "Order Fulfillment Options",
        "Shipping and Delivery",
        "Emerging E-commerce Trends",
        "The Future of E-commerce",
        "Analyzing Successful E-commerce Businesses",
        "E-commerce Project",
      ],
    },
    {
      number: 5,
      title: "Photography and Video Engineering",
      badges: [],
      topics: [
        "Core Photography Principles",
        "Photography for Branding & Storytelling",
        "Commercial & Product Photography",
        "Video Production Fundamentals",
        "Video Editing Software",
        "Video Marketing and Storytelling",
      ],
    },
  ],
};
