// import JoinTeam from "@components/joinTeam";
import styles from "./style.module.scss";

export const metadata = {
  title: "Digital Academy 360 | Privacy Policy",
  description:
    "The Privacy Policy document at Digital Academy 360 contains information that is collected and stored by Digital Academy 360 as well as how we utilize it",
  keywords: ["Digital Academy 360 Privacy Policy,DA 360 Privacy Policy"],
  robots:
    "index, follow, max-snippet:-1, max-video-preview:-1, max-image-preview:large",
  alternates: {
    canonical: "https://digitalacademy360.com/da360-privacy-policy",
  },
  openGraph: {
    title: "Digital Academy 360 | Privacy Policy",
    description:
      "The Privacy Policy document at Digital Academy 360 contains information that is collected and stored by Digital Academy 360 as well as how we utilize it",
    url: "https://digitalacademy360.com/da360-privacy-policy",
    siteName: "Digital Academy 360",
    locale: "en_US",
    type: "website",
    images: ["https://digitalacademy360.com/og-image.jpg"],
  },
  twitter: {
    card: "summary_large_image",
    title: "Digital Academy 360 | Privacy Policy",
    description:
      "The Privacy Policy document at Digital Academy 360 contains information that is collected and stored by Digital Academy 360 as well as how we utilize it",
    images: ["https://digitalacademy360.com/og-image.jpg"],
  },
};

export default function PrivacyPolicy() {
  return (
    <main>
      <section className={styles.contentSection}>
        <div className="container">
          <div className="row">
            <div className="col-lg-12">
              <div className={styles.contentBox}>
                <div className={styles.contentItem}>
                  <h2>
                    Last updated on Wednesday, 20 August 2025 <br /> Place:
                    Bangalore, Karnataka
                  </h2>
                  <p>
                    Welcome to https://digitalacademy360.com/, this Website is
                    owned and operated by Digital Academy 360 Pvt. Ltd., having
                    its registered office at No 57, Ground Floor, 8th, Near
                    State Bank of India, J P Nagar, Bangalore, Bangalore South,
                    Karnataka, India, 560078. By using our Digital Academy 360
                    services, you are agreeing to be bound by our terms and
                    conditions.{" "}
                  </p>
                  <p>
                    If this document is not in a language that you understand,
                    you shall contact Digital Academy 360 at the email
                    info@da360.ai, Failure to do so within 24 (Twenty-Four)
                    hours from the time of receipt of this document and your
                    acceptance of this document shall be considered as your
                    understanding of this document.
                  </p>
                  <p>
                    This electronic record is generated by a computer system and
                    does not require any physical or digital signatures. By
                    visiting our website or availing our services including
                    enrolling in offered courses, you are consenting to be bound
                    by this User Agreement. Please ensure that you read and
                    understand all the provisions of this document before you
                    start using the Digital Academy 360, as you shall be bound
                    by all the terms and conditions herein of this electronic
                    contract. If you do not agree or accept any of the Terms and
                    Conditions contained herein, then please do not use the
                    Digital Academy 360’s digital platform or avail any of the
                    services being provided therein.
                  </p>
                  <p>
                    The Digital Academy 360 Pvt. Ltd. or any of its affiliates
                    or associate companies or subsidiaries (hereafter
                    collectively referred as “Digital Academy 360&quot;, “we”,
                    “us”, or “our”), prescribes this Privacy Policy (the
                    “Privacy Policy” / “Policy”), last updated on the date
                    mentioned above, describes how we collect, use, and disclose
                    your Personal Information when you visit or use our website
                    (the “Digital Platform”), the Digital Academy 360 email
                    plugins, the Digital Academy 360 chrome extension and any
                    other website or mobile application or plugins that links to
                    this Privacy Policy in Our capacity as a controller of your
                    Personal Information.
                  </p>
                  <p>
                    This Privacy Policy explains what information of yours will
                    be collected when you access the Services, how such Personal
                    Information will be used, and how you can control the
                    collection, correction and/or deletion of your Personal
                    Information. We will not use or share your Personal
                    Information with anyone except as described in this Privacy
                    Policy. The use of information collected through our digital
                    platform shall be limited to the purposes under this Privacy
                    Policy and our Terms of Service (the “Terms”) to users.
                    Capitalised terms not specifically defined herein shall have
                    the same meaning as ascribed to them in the Terms.
                  </p>
                  <p>
                    By visiting our digital platform and accessing the
                    information, services, and learning courses we provide, you
                    understand and agree to accept and adhere to the following
                    terms and conditions as stated in this policy (hereafter
                    referred to as &apos;User Agreement&apos;), along with the
                    terms and conditions as stated in our Privacy Policy.
                  </p>
                  <p>
                    We reserve the right to change this User Agreement from time
                    to time without notice. You acknowledge and agree that it is
                    your responsibility to review this User Agreement
                    periodically to familiarize yourself with any modifications.
                    Your continued use of this site after such modifications
                    will constitute acknowledgment and agreement of the modified
                    terms and conditions.
                  </p>
                  <p>
                    Reading this privacy notice will help you understand your
                    privacy rights and choices. If you do not agree with our
                    policies and practices, please do not use our Services. If
                    you still have any questions or concerns, please contact us
                    at info@da360.ai.
                  </p>
                </div>
                <div className={styles.contentItem}>
                  <h2>Summary of Key Points</h2>
                  <p>
                    <strong>Personal Information Processing:</strong> The
                    Digital Academy 360 Pvt. Ltd. processes personal information
                    when you interact with Digital Academy 360 and its Services,
                    based on your choices, interactions, and product usage.
                  </p>
                  <p>
                    <strong>Sensitive Personal Information:</strong> Sensitive
                    personal information may be processed with your consent or
                    as permitted by law.
                  </p>
                  <p>
                    <strong>Information from Third Parties:</strong> Digital
                    Academy 360 Pvt. Ltd. may receive information from various
                    sources such as public databases, marketing partners, and
                    social media platforms.
                  </p>
                  <p>
                    <strong>Information Processing:</strong> Your information is
                    processed to provide, improve, and administer our Services,
                    communicate with you, ensure security, prevent fraud, and
                    comply with the law. Consent may also be sought for other
                    purposes.
                  </p>
                  <p>
                    <strong>Sharing Personal Information:</strong> Digital
                    Academy 360 Pvt. Ltd. shares information with specific third
                    parties in particular situations.
                  </p>
                  <p>
                    <strong>Information Security:</strong> While Digital Academy
                    360 Pvt. Ltd. has measures in place to safeguard your
                    personal information, we cannot guarantee complete security
                    against unauthorized access or modification by hackers or
                    cybercriminals.
                  </p>
                  <p>
                    <strong>Your Rights:</strong> Depending on your location,
                    you may have specific rights regarding your personal
                    information under applicable privacy laws.
                  </p>
                  <p>
                    <strong>Exercising Your Rights:</strong> To exercise your
                    rights, you can email us at [info@da360.ai] or contact us,
                    and Digital Academy 360 Pvt. Ltd. will address your request
                    as per relevant data protection laws.
                  </p>
                </div>
                <div className={styles.contentItem}>
                  <h2>1. Overview of the Policy</h2>
                  <p>
                    1.1. This privacy policy contains information on our website
                    https://digitalacademy360.com/, and applies to the Users of
                    Digital Academy 360 Services anywhere in India, including
                    the Users of its features and other services. This Privacy
                    Policy describes how Digital Academy 360 and its affiliates
                    collect and use your data.
                  </p>
                  <p>
                    1.2. This https://digitalacademy360.com/ and its other
                    digital platforms are digital property owned and operated by
                    Digital Academy 360 Pvt. Ltd.. The Digital Academy 360 is
                    committed to protecting and respecting your privacy. We do
                    collect your personal information and process your data
                    following the Information Technology Act, 2000 (also known
                    as ITA-2000, or the IT Act), Digital Personal Data
                    Protection Act, 2023, and other national and state laws that
                    relate to the processing of your personal data.
                  </p>
                  <p>
                    1.3. The Digital Academy 360 Pvt. Ltd. collects your
                    information to provide and continually improve our services.
                    Our Privacy Policy is subject to change at any time without
                    notice, to make sure you are aware of any changes, please
                    review this Policy periodically. All the Partners and
                    Independent Partners who are working with or for us, or who
                    have access to personal information, will be expected to
                    read and comply with this Policy. No third party may access,
                    or process sensitive personal information held by us without
                    having first entered into a Confidentiality Agreement
                  </p>
                </div>
                <div className={styles.contentItem}>
                  <h2>2. Collection of your Information</h2>
                  <p>
                    2.1. We are dedicated to upholding your online privacy and
                    recognize the importance of safeguarding any Personal
                    Information you share with us. The following information may
                    be collected:
                  </p>
                  <ul>
                    <li>
                      2.1.1. Personal Data:
                      <ul>
                        <li>
                          2.1.1.1. Name, Address, Password, Email ID, Mobile
                          Number
                        </li>
                        <li>
                          2.1.1.2. Educational Details, Qualifications, College
                          Name, Area of Interest, References, etc.
                        </li>
                      </ul>
                    </li>
                    <li>
                      2.1.2. Tracking Information:
                      <ul>
                        <li>
                          2.1.2.1. IP address and Device ID when connected to
                          the Internet.
                        </li>
                        <li>
                          2.1.2.2. Includes URLs visited, computer browser
                          information, and interactions with the Site and App.
                        </li>
                      </ul>
                    </li>
                    <li>
                      2.1.3. Privacy Policy Applicability:
                      <ul>
                        <li>
                          2.1.3.1. Applies to all users, including
                          non-registered members.
                        </li>
                        <li>
                          2.1.3.2. Includes browsing behavior, pages viewed, and
                          personal information provided on the Site.
                        </li>
                      </ul>
                    </li>
                    <li>
                      2.1.4. Collection Purposes:
                      <ul>
                        <li>
                          2.1.4.1. Enable the provision of services requested by
                          you.
                        </li>
                        <li>
                          2.1.4.2. Communicate necessary account and
                          service-related information.
                        </li>
                        <li>
                          2.1.4.3. Facilitate quality customer care services.
                        </li>
                        <li>
                          2.1.4.4. Comply with applicable laws, rules, and
                          regulations.
                        </li>
                      </ul>
                    </li>
                    <li>
                      2.1.5. Sharing Information:
                      <ul>
                        <li>
                          2.1.5.1. Necessary information may be shared with
                          third parties to fulfill service requests.
                        </li>
                        <li>
                          2.1.5.2. Contact information may be used to send
                          offers based on interests and prior activity.
                        </li>
                        <li>
                          2.1.5.3. Internal use of contact information for
                          service improvement efforts.
                        </li>
                      </ul>
                    </li>
                    <li>
                      2.1.6. Search Details:
                      <ul>
                        <li>
                          2.1.6.1. Search history, usage details, and time spent
                          on the Website is collected and stored.
                        </li>
                      </ul>
                    </li>
                    <li>
                      2.1.7. Payment Information:
                      <ul>
                        <li>
                          2.1.7.1. Financial information provided for
                          transactions is stored securely.
                        </li>
                        <li>
                          2.1.7.2. Transacted over approved payment gateways
                          with encryption for protection.
                        </li>
                        <li>
                          2.1.7.3. Stored in internal Company servers for a
                          finite period, deleted upon termination of users.
                        </li>
                      </ul>
                    </li>
                    <li>
                      2.1.8. Usage Options:
                      <ul>
                        <li>
                          2.1.8.1. Option to withhold specific information.
                        </li>
                        <li>
                          2.1.8.2. Opt-out of non-essential communications and
                          services.
                        </li>
                        <li>
                          2.1.8.3. Choice to not use certain features or
                          services on the Site.
                        </li>
                      </ul>
                    </li>
                    <li>
                      2.1.9. Internet Security Practices:
                      <ul>
                        <li>
                          2.1.9.1. Users are advised to follow security
                          practices to mitigate risks.
                        </li>
                        <li>
                          2.1.9.2. Report suspicious activity or compromised
                          accounts to customer care.
                        </li>
                      </ul>
                    </li>
                    <li>
                      2.1.10. User Rights:
                      <ul>
                        <li>
                          2.1.10.1. Access, rectify, or alter personally
                          identifiable information.
                        </li>
                        <li>
                          2.1.10.2. Restrict the level of information retained.
                        </li>
                        <li>
                          2.1.10.3. Object to the retention, use, and potential
                          disclosure of personally identifiable information at
                          any stage of information collection.
                        </li>
                      </ul>
                    </li>
                  </ul>
                </div>
                <div className={styles.contentItem}>
                  <h2>3. Access to your Personal Information</h2>
                  <p>
                    3.1. Registered users have the right to view the categories
                    of personal information collected about them.
                  </p>
                  <p>
                    3.2. This information is accessible within the Profile
                    section of the user account.
                  </p>
                  <p>
                    3.3. However, certain information may be withheld if its
                    disclosure poses a significant risk to the user, their
                    personal information, or the business.
                  </p>
                  <p>
                    3.4. For instance, account passwords may not be disclosed
                    for security reasons.
                  </p>
                </div>
                <div className={styles.contentItem}>
                  <h2>4. Use of your Information</h2>
                  <p>
                    4.1. The Digital Academy 360 Pvt. Ltd. shall use the
                    information for the following purposes:
                  </p>
                  <ul>
                    <li>
                      4.1.1. Your provided information will be used to contact
                      you when necessary.
                    </li>
                    <li>
                      4.1.2. It will also be utilized for targeted marketing
                      campaigns, including email marketing, remarketing, and
                      look-alike campaigns.
                    </li>
                    <li>
                      4.1.3. The data provided by you may be used to conduct
                      surveys and gain insights.
                    </li>
                    <li>
                      4.1.4. Additional data may be linked through third-party
                      data providers or analyzed with the help of analytics
                      service providers.
                    </li>
                    <li>
                      4.1.5. Your information will be used to improve existing
                      products, services, and features.
                    </li>
                    <li>
                      4.1.6. Purchase, usage, and traffic data will be analyzed
                      to understand user behavior and preferences.
                    </li>
                    <li>
                      4.1.7. To manage Your Account: To manage Your registration
                      as a user of the Service. The Personal Data You provide
                      can give You access to different functionalities of the
                      Service that are available to You as a registered user.
                    </li>
                    <li>
                      4.1.8. For the performance of a contract: The development,
                      compliance, and undertaking of the purchase contract for
                      the services You have purchased or of any other contract
                      with Us through the Service.
                    </li>
                    <li>
                      4.1.9. To provide You with news, special offers, and
                      general information about other goods, services, and
                      events that we offer that are similar to those that you
                      have already purchased or enquired about unless You have
                      opted not to receive such information.
                    </li>
                    <li>
                      4.1.10. For other purposes: We may use Your information
                      for other purposes, such as data analysis, identifying
                      usage trends, determining the effectiveness of our
                      promotional campaigns, and evaluating and improving our
                      Service, products, services, marketing, and your
                      experience.
                    </li>
                  </ul>
                </div>
                <div className={styles.contentItem}>
                  <h2>5. Disclosure of Personal Information</h2>
                  <p>
                    5.1. We may share or disclose your personal information in
                    the following situations:
                  </p>
                  <ul>
                    <li>
                      5.1.1. With Service Providers: We may share Your personal
                      information with Service Providers to monitor and analyze
                      the use of our Service, for payment processing, and to
                      contact You.
                    </li>
                    <li>
                      5.1.2. For business transfers: We may share or transfer
                      Your personal information in connection with, or during
                      negotiations of, any merger, sale of Company assets,
                      financing, or acquisition of all or a portion of Our
                      business to another company.
                    </li>
                    <li>
                      5.1.3. With Affiliates: We may share Your information with
                      Our affiliates, in which case we will require those
                      affiliates to honor this Privacy Policy. Affiliates
                      include Our parent company and any other subsidiaries,
                      joint venture partners, or other companies that We control
                      or that are under common control with Us.
                    </li>
                    <li>
                      5.1.4. With business partners: We may share Your
                      information with Our business partners to offer You
                      certain customized plans, services, or promotions.
                    </li>
                    <li>
                      5.1.5. With other users: When you share personal
                      information or otherwise interact in public areas with
                      other users, such information may be viewed by all users
                      and may be publicly distributed outside.
                    </li>
                  </ul>
                  <p>
                    5.2. Affiliated partners like exhibitors, sponsors, and
                    advertisers may receive membership lists or event attendance
                    lists containing your full name, address, company name, and
                    email address.
                  </p>
                  <p>
                    5.3. We are not responsible for the use or misuse of your
                    personal information by these affiliated partners.
                  </p>
                  <p>
                    5.4. Your personal data and sensitive personal data may be
                    collected and stored by us for internal record-keeping
                    purposes.
                  </p>
                  <p>
                    5.5. We utilize tracking information such as IP addresses
                    and device IDs to identify users and gather broad
                    demographic information.
                  </p>
                  <p>
                    5.6. Personal information will not be sold, licensed, or
                    traded.
                  </p>
                  <p>
                    5.7. Your personal information will not be shared with
                    others unless they are acting under our instructions or
                    required to do so by law.
                  </p>
                  <p>
                    5.8. Information collected via server logs includes users’
                    IP addresses and visited pages, used for managing the web
                    system and troubleshooting problems.
                  </p>
                  <p>
                    5.9. Third-party analytics, tracking, optimization, and
                    targeting tools are used to understand user engagement with
                    our website and improve it, as well as to provide
                    personalized content and ads based on user preferences.
                  </p>
                  <p>
                    5.10. We may share users’ data if we believe it’s required
                    by applicable law, regulation, operating license or
                    agreement, legal process, or governmental request, or where
                    the disclosure is otherwise appropriate due to safety or
                    similar concerns. This includes sharing personal data with
                    law enforcement officials, public health officials, other
                    government authorities, or other third parties as necessary
                    to enforce our Terms of Service, user agreements, or other
                    policies; to protect our rights or property or the rights,
                    safety, or property of others; or in the event of a claim or
                    dispute relating to the use of our services.
                  </p>
                </div>
                <div className={styles.contentItem}>
                  <h2>6. Procedure for Collecting Information</h2>
                  <p>
                    6.1. Before or at the time of collecting personal
                    information, the purposes for which information is being
                    collected will be identified.
                  </p>
                  <p>
                    6.2. Personal information will be collected and used solely
                    to fulfill the purposes specified by Digital Academy 360
                    Pvt. Ltd..
                  </p>
                  <p>
                    6.3. Collection and usage will be within the scope of the
                    consent of the individual concerned or as required by law.
                  </p>
                  <p>
                    6.4. Personal information will only be retained for as long
                    as necessary to fulfill the specified purposes.
                  </p>
                  <p>
                    6.5. Personal information will be collected by lawful and
                    fair means.
                  </p>
                  <p>
                    6.6. Collection will be done with the knowledge and consent
                    of the individual concerned.
                  </p>
                  <p>
                    6.7. Personal data should be relevant to the purposes for
                    which it is to be used.
                  </p>
                  <p>
                    6.8. It should also be accurate, complete, and up-to-date to
                    the extent necessary for those purposes.
                  </p>
                </div>

                <div className={styles.contentItem}>
                  <h2>7. Data Storage & Transfer</h2>
                  <p>
                    7.1. Your Personal Information and files including their
                    backups are processed and stored on our servers and the
                    servers of companies we hire to provide services to Us. Your
                    Personal Information may be transferred across national
                    borders because We may have servers located outside India,
                    and the companies we hire to help us run our business may be
                    located in different countries around the world.
                  </p>
                  <p>
                    7.2. Your consent to this Privacy Policy followed by Your
                    submission of such information represents Your agreement to
                    that transfer.
                  </p>
                  <p>
                    7.3. We will take all steps reasonably necessary to ensure
                    that Your data is treated securely and in accordance with
                    this Privacy Policy and no transfer of Your Data will take
                    place to an organization or a country unless there are
                    adequate controls in place by the data protection laws
                    including the security of Your data and other personal
                    information.
                  </p>
                </div>

                <div className={styles.contentItem}>
                  <h2>8. Retention of your Personal Data</h2>
                  <p>
                    8.1. We will retain Your Data only for as long as is
                    necessary for the purposes set out in this Privacy Policy.
                    We will retain and use Your Data to the extent necessary to
                    comply with our legal obligations (for example, if we are
                    required to retain your data to comply with applicable
                    laws), resolve disputes, and enforce our legal agreements
                    and policies.
                  </p>
                  <p>
                    8.2. We retain the Personal Information collected where an
                    ongoing legitimate business requires the retention of such
                    Personal Information. In the absence of a need to retain
                    your Personal Information as specified herein, we will
                    either delete or aggregate your Personal Information or, if
                    this is not possible then We will securely store your
                    Personal Information and isolate it from any further
                    processing until deletion is possible.
                  </p>
                  <p>
                    8.3. We will also retain Usage Data for internal analysis
                    purposes. Usage Data is generally retained for a shorter
                    period, except when this data is used to strengthen the
                    security or to improve the functionality of Our Service, or
                    We are legally obligated to retain this data for longer
                    periods.
                  </p>
                </div>

                <div className={styles.contentItem}>
                  <h2>9. Data Deletion Request</h2>
                  <p>
                    9.1. You have the right to request the deletion of any
                    personal information collected from/about you.
                  </p>
                  <p>
                    9.2. This can be done by sending an email to info@da360.ai
                  </p>
                  <p>
                    9.3. However, we may retain personal information as
                    authorized under applicable law.
                  </p>
                  <p>
                    9.4. Retention may be necessary for purposes such as
                    providing services, protecting against fraudulent activity,
                    complying with law enforcement requests, internal purposes
                    related to your relationship with us, or fulfilling legal or
                    financial compliance obligations.
                  </p>
                </div>

                <div className={styles.contentItem}>
                  <h2>10. Data requests from the Law Enforcement Agency</h2>
                  <p>
                    10.1. We do not sell, trade, or otherwise transfer your
                    Personal Information except in accordance with this Policy.
                  </p>
                  <p>
                    10.2. We do not share any information that directly
                    identifies you with any third party, except in the following
                    limited cases:
                  </p>
                  <ul>
                    <li>
                      10.2.1. As required to comply with applicable law or
                      regulation, or to comply with law enforcement;
                    </li>
                    <li>
                      10.2.2. To respond to claims and/or legal processes;
                    </li>
                    <li>
                      10.2.3. To protect our rights or our property, or to
                      enforce our Terms of Service;
                    </li>
                    <li>
                      10.2.4. To help ensure the safety of the public or an
                      individual;
                    </li>
                    <li>
                      10.2.5. To prevent behavior that is (or that we think may
                      be) illegal or unethical;
                    </li>
                    <li>
                      10.2.6. With your consent, or at your request or
                      direction; or
                    </li>
                    <li>10.2.7. As otherwise outlined in this Policy.</li>
                  </ul>
                </div>

                <div className={styles.contentItem}>
                  <h2>11. Cookies and Web Beacons</h2>
                  <p>11.1. Use of Cookies:</p>
                  <ul>
                    <li>
                      11.1.1. Data collection devices like &quot;cookies&quot;
                      are used on certain pages of our website.
                    </li>
                    <li>
                      11.1.2. Cookies are small files placed on your hard drive
                      to assist in providing customized services.
                    </li>
                  </ul>
                  <p>11.2. Functionality of Cookies:</p>
                  <ul>
                    <li>
                      11.2.1. Certain features are available only through the
                      use of a cookie.
                    </li>
                    <li>
                      11.2.2. Cookies help provide information targeted to your
                      interests and may identify logged-in or registered users.
                    </li>
                  </ul>
                  <p>11.3. Session Cookies:</p>
                  <ul>
                    <li>
                      11.3.1. Our website uses session cookies to ensure a good
                      user experience.
                    </li>
                    <li>
                      11.3.2. These cookies contain a unique number, your
                      &apos;session ID&apos;, allowing our server to recognize
                      your computer and remember your actions on the Site.
                    </li>
                  </ul>
                  <p>11.4. Benefits of Session Cookies:</p>
                  <ul>
                    <li>
                      11.4.1. You only need to log in once when navigating
                      secure areas of the Site.
                    </li>
                    <li>
                      11.4.2. Our server can distinguish between your computer
                      and other users, ensuring you see the requested
                      information.
                    </li>
                  </ul>
                </div>

                {/*  */}
                <div className={styles.contentItem}>
                  <h2>12. Log Files</h2>
                  <p>
                    12.1. At Digital Academy 360, accessible via
                    https://digitalacademy360.com/, we adhere to standard
                    industry practices by utilizing log files. These files
                    record data from visitors upon accessing our website, a
                    common procedure employed by hosting services for analytical
                    purposes. The data collected through log files includes, but
                    is not limited to, Internet Protocol (IP) addresses, browser
                    type, Internet Service Provider (ISP), date and time stamps,
                    referring and exit pages, and, where applicable, the number
                    of clicks. Such information is not associated with any
                    personally identifiable data. The collection of this data
                    serves the purposes of analyzing trends, administering the
                    website, monitoring user navigation patterns, and compiling
                    demographic information.
                  </p>
                </div>

                <div className={styles.contentItem}>
                  <h2>13. Google Analytics</h2>
                  <p>
                    13.1. We utilize Google Analytics to understand how users
                    interact with our content and improve user experience. These
                    cookies track your progress on our website and digital
                    platform, collecting anonymous data such as your origin,
                    visited pages, and time spent on the digital platform.
                  </p>
                  <p>
                    13.2. Information generated by the cookie, including your IP
                    address, may be transmitted to and stored by Google on their
                    servers situated in the respective country.
                  </p>
                  <p>
                    13.3. Google may use this information to evaluate website
                    usage, compile reports for us, and provide other related
                    services. Google may also transfer this information to third
                    parties as required by law or for processing on
                    Google&apos;s behalf. However, Google will not associate
                    your IP address with any other data held by Google.
                  </p>
                  <p>
                    13.4. By using our website, you consent to Google processing
                    data about you as described above. Further information about
                    Analytics and Google&apos;s privacy policy can be found on
                    the Google website.
                  </p>
                  <p>
                    13.5. Google Double Click DART Cookie: Google, as a
                    third-party vendor on our website, employs cookies,
                    specifically DART cookies, to deliver advertisements to
                    visitors based on their interactions with
                    https://digitalacademy360.com/ and other websites on the
                    internet. Visitors may opt out of the use of DART cookies by
                    accessing the Google Advertising and Content Network Privacy
                    Policy at the following URL:{" "}
                    <a
                      href="https://policies.google.com/technologies/ads"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      https://policies.google.com/technologies/ads
                    </a>
                    .
                  </p>
                </div>

                <div className={styles.contentItem}>
                  <h2>14. External links on the Website</h2>
                  <p>14.1. Inclusion of External Links:</p>
                  <ul>
                    <li>
                      14.1.1. The Website may contain advertisements and
                      hyperlinks to other websites, applications, content, or
                      resources.
                    </li>
                    <li>
                      14.1.2. These external links are provided by companies or
                      persons other than Digital Academy 360 Pvt. Ltd..
                    </li>
                  </ul>
                  <p>14.2. Lack of Control:</p>
                  <ul>
                    <li>
                      14.2.1. We do not have control over these external sites
                      or resources.
                    </li>
                    <li>
                      14.2.2. We are not responsible for their availability or
                      endorse any advertising, services/products, or other
                      materials on or available from such websites or resources.
                    </li>
                  </ul>
                  <p>14.3. Disclaimer of Liability:</p>
                  <ul>
                    <li>
                      14.3.1. We are not liable for any loss or damage incurred
                      by you because of the availability of these external sites
                      or resources.
                    </li>
                    <li>
                      14.3.2. We are also not liable for any reliance placed by
                      you on the completeness, accuracy, or existence of any
                      advertising, products, or other materials on, or available
                      from, such websites or resources.
                    </li>
                  </ul>
                  <p>14.4. External Privacy Policies:</p>
                  <ul>
                    <li>
                      14.4.1. External websites and resource providers may have
                      their privacy policies governing the collection, storage,
                      retention, and disclosure of Your Personal Information.
                    </li>
                    <li>
                      14.4.2. We recommend reviewing their privacy policy upon
                      entering the external website.
                    </li>
                  </ul>
                </div>

                <div className={styles.contentItem}>
                  <h2>15. Exercising Your Rights</h2>
                  <p>
                    15.1. Unless subject to an exemption, you have the following
                    rights concerning your data:
                  </p>
                  <ul>
                    <li>
                      15.1.1. Right to Access: You have the right to request a
                      copy of your data held by the Digital Academy 360 Pvt.
                      Ltd..
                    </li>
                    <li>
                      15.1.2. Right to Rectification: You can request correction
                      of any inaccurate or outdated personal data.
                    </li>
                    <li>
                      15.1.3. Right to Withdraw Consent: You have the right to
                      withdraw your consent to the processing of your data at
                      any time.
                    </li>
                    <li>
                      15.1.4. Right to Object: You can object to the processing
                      of your data.
                    </li>
                    <li>
                      15.1.5. Right to Lodge a Complaint: You have the right to
                      complain with a supervisory authority.
                    </li>
                    <li>
                      15.1.6. Right to Information on Data Transfer: You have
                      the right to obtain information on whether your data are
                      transferred to a third country or international
                      organization.
                    </li>
                  </ul>
                </div>

                <div className={styles.contentItem}>
                  <h2>16. Your Rights under the DPDP Act</h2>
                  <p>
                    16.1. You may exercise Your rights of access, rectification,
                    cancellation, and opposition by “Contacting Us”. Please note
                    that we may ask You to verify Your identity before
                    responding to such requests. If You make a request, we will
                    try our best to respond to You as soon as possible.
                  </p>
                  <p>
                    16.2. Please Note, we may process Personal Data under the
                    following conditions:
                  </p>
                  <ul>
                    <li>16.2.1. If you have given your consent;</li>
                    <li>16.2.2. Performance of a contract;</li>
                    <li>16.2.3. Legal obligations;</li>
                    <li>16.2.4. To protect your vital interests;</li>
                    <li>16.2.5. In Public and Legitimate Interests.</li>
                  </ul>
                  <p>
                    16.3. Your Rights under the DPDP: we undertake to respect
                    the confidentiality of Your Data and to guarantee You can
                    exercise Your rights. You have the right under this Privacy
                    Policy, and by law if You are within the Indian territory,
                    to:
                  </p>
                  <ul>
                    <li>16.3.1. Request access to Your Data;</li>
                    <li>16.3.2. Request correction of the Personal Data;</li>
                    <li>16.3.3. Object to processing of Your Data;</li>
                    <li>16.3.4. Request erasure of Your Data;</li>
                    <li>16.3.5. Request the transfer of Your Data;</li>
                    <li>16.3.6. Withdraw Your consent.</li>
                  </ul>
                  <p>
                    16.4. In any case, we will gladly help to clarify the
                    specific legal basis that applies to the processing, and in
                    particular whether the provision of Personal Data is a
                    statutory or contractual requirement, or a requirement
                    necessary to enter into a contract.
                  </p>
                </div>

                <div className={styles.contentItem}>
                  <h2>17. Password Control</h2>
                  <p>
                    17.1. When you sign up or register as a learner or user or
                    student, you will be prompted to choose a password. It is
                    your responsibility to maintain the confidentiality of your
                    password. To safeguard your account and information, follow
                    these guidelines:
                  </p>
                  <ul>
                    <li>
                      17.1.1. Choose Carefully: Select a strong, unique password
                      and refrain from sharing it with others.
                    </li>
                    <li>
                      17.1.2. Secure Your Computer: Keep your password and
                      computer secure. Sign out after using our services to
                      prevent unauthorized access.
                    </li>
                    <li>
                      17.1.3. No Sharing: Do not use another Student&apos;s
                      account, username, email address, or password at any time,
                      nor disclose your password to third parties.
                    </li>
                    <li>
                      17.1.4. Account Responsibility: You are accountable for
                      all activities conducted with your login information and
                      password, including any associated fees.
                    </li>
                    <li>
                      17.1.5. Immediate Action on Compromise: If your password
                      is compromised, promptly change it to maintain control
                      over your personally identifiable information. Notify us
                      immediately if you suspect unauthorized account use or
                      access, even after changing your password.
                    </li>
                  </ul>
                </div>

                <div className={styles.contentItem}>
                  <h2>18. Protection of your Data</h2>
                  <p>
                    18.1. We consider data to be an asset that requires
                    safeguarding against loss and unauthorized access. To ensure
                    the security of your data, we implement various security
                    measures to prevent unauthorized access by individuals both
                    inside and outside the Company. Our approach includes:
                  </p>
                  <ul>
                    <li>
                      18.1.1. Employing Diverse Security Techniques: We utilize
                      a range of security techniques to safeguard data, ensuring
                      protection against unauthorized access.
                    </li>
                    <li>
                      18.1.2. Adhering to Industry Standards: Our security
                      measures align with generally accepted industry standards.
                      This ensures the protection of Personal Information
                      submitted to us and any information accessed by our
                      systems.
                    </li>
                    <li>
                      18.1.3. Continuous Monitoring and Improvement: We
                      regularly monitor our security protocols and update them
                      as needed to address evolving threats and maintain robust
                      data protection.
                    </li>
                    <li>
                      18.1.4. Comprehensive Security Measures: Our security
                      framework encompasses multiple layers of protection,
                      including encryption, access controls, and intrusion
                      detection systems, among others.
                    </li>
                    <li>
                      18.1.5. Commitment to Data Protection: We are dedicated to
                      upholding the highest standards of data protection to
                      maintain the confidentiality, integrity, and availability
                      of your information.
                    </li>
                  </ul>
                  <p>
                    18.2. By implementing these measures, we strive to uphold
                    the security and integrity of your data, adhering to
                    industry best practices and regulatory requirements.
                  </p>
                </div>

                <div className={styles.contentItem}>
                  <h2>19. Marketing, Advertisement & Preference</h2>
                  <p>
                    19.1. We use your personal information to send you marketing
                    by post, telephone, social media platforms, email, SMS,
                    Website notifications, and silent notifications to track the
                    installation status of the Website. We may also use your
                    personal information to carry out online paid marketing
                    activities like retargeting.
                  </p>
                  <p>
                    19.2. We may permit certain third-party companies to help us
                    tailor advertising that we think may be of interest to users
                    and to collect and use other data about user activities on
                    the Website or App. These companies may deliver ads that
                    might place cookies and otherwise track user behavior.
                  </p>
                  <p>
                    19.3. We also use technology to help us understand your
                    personal preferences and interests so that we can send
                    recommendations and marketing communications that are likely
                    to be of more interest to you. Using technology in this way
                    is sometimes known as profiling.
                  </p>
                  <p>
                    19.4. Some of the advertisers on our site may use cookies
                    and web beacons. Each of our advertising partners has their
                    own Privacy Policy for their policies on user data. For
                    easier access, we hyperlinked to their Privacy Policies
                    below. Google:{" "}
                    <a
                      href="https://policies.google.com/technologies/ads"
                      target="_blank"
                      rel="noopener noreferrer"
                    >
                      https://policies.google.com/technologies/ads
                    </a>
                    .
                  </p>
                </div>

                <div className={styles.contentItem}>
                  <h2>20. Legal Basis</h2>
                  <p>
                    20.1. Our legal basis for collecting and using the Personal
                    Information described above will depend on the Personal
                    Information concerned and the specific context in which We
                    collect it. We will normally collect Personal Information
                    from you only where it is needed to perform a contract with
                    you, where the processing is in Our legitimate interests and
                    not overridden by your data protection interests or
                    fundamental rights and freedoms, or where We have your
                    consent. In some cases, we may also have a legal obligation
                    to collect Personal Information from you.
                  </p>
                  <p>
                    20.2. If We process your Personal Information with reliance
                    on your consent, you may withdraw your consent at any time.
                    If you have questions or need further information concerning
                    the legal basis on which we collect and use your Personal
                    Information, please contact Us at info@da360.ai.
                  </p>
                </div>

                <div className={styles.contentItem}>
                  <h2>21. Privacy of Children</h2>
                  <p>
                    21.1. The Digital Academy 360 recognizes the importance of
                    children&apos;s safety and privacy. We do not request, or
                    knowingly collect, any personally identifiable information
                    from children under the age of 13. The Digital Academy 360
                    is very sensitive to privacy issues regarding children. If a
                    parent or guardian becomes aware that his or her child has
                    provided us with Personal Information, he or she should
                    write to us at info@da360.ai.
                  </p>
                </div>

                <div className={styles.contentItem}>
                  <h2>22. Security</h2>
                  <p>
                    22.1. Your Personal Information is extremely important to
                    us. Your information resides on a secure server that only
                    selected personnel have access to. Promotional and referral
                    codes are random alphanumeric sequences that are encrypted.
                    In addition to our precautions, it is important that you do
                    not share your password with anyone. Although we try our
                    best to protect your information, we cannot eliminate
                    security risks associated with Personal Information.
                  </p>
                  <p>
                    22.2. You have the right to request the deletion of Your
                    Data, subject to certain exceptions. Once We receive and
                    confirm Your request, we will delete (and direct Our Service
                    Providers to delete) Your personal information from our
                    records, unless an exception applies. We may deny Your
                    deletion request if retaining the information is necessary
                    for Us or Our Service Providers to:
                  </p>
                  <ul>
                    <li>
                      22.2.1. Comply with a legal obligation or to complete the
                      transaction for which We collected the personal
                      information, provide a good or service that You requested,
                      take actions reasonably anticipated within the context of
                      our ongoing business relationship with You, or otherwise
                      perform our contract with You.
                    </li>
                    <li>
                      22.2.2. Exercise free speech, ensure the right of another
                      consumer to exercise their free speech rights, or exercise
                      another right provided for by law.
                    </li>
                    <li>
                      22.2.3. Engage in public or peer-reviewed scientific,
                      historical, or statistical research in the public interest
                      that adheres to all other applicable ethics and privacy
                      laws, when the information&apos;s deletion may likely
                      render impossible or seriously impair the research&apos;s
                      achievement if You previously provided informed consent.
                    </li>
                    <li>
                      22.2.4. Enable solely internal uses that are reasonably
                      aligned with consumer expectations based on Your
                      relationship with Us.
                    </li>
                    <li>
                      22.2.5. Make other internal and lawful uses of that
                      information that are compatible with the context in which
                      You provided it.
                    </li>
                  </ul>
                </div>

                <div className={styles.contentItem}>
                  <h2>23. Review & Update</h2>
                  <p>
                    23.1. We may update Our Privacy Policy annually. We will
                    notify You of any changes by posting the new or updated
                    Privacy Policy on this page.
                  </p>
                  <p>
                    23.2. The most recent version of the policy will govern our
                    use of your information and will always be available on the
                    Website of the Digital Academy 360.
                  </p>
                  <p>
                    23.3. We will let You know via email and/or a prominent
                    notice on Our Service, before the change becomes effective
                    and update the “Last updated” date at the top of this
                    Privacy Policy.
                  </p>
                </div>

                <div className={styles.contentItem}>
                  <h2>24. Contact Us</h2>
                  <p>
                    24.1. If you have any questions about this Privacy Policy,
                    the practices or your dealings with this Digital Academy 360
                    and you would like to ask about or complain about how we
                    process your personal information, please contact us for
                    support, or mail us at one of the addresses below:
                  </p>
                  <p>
                    Digital Academy 360 Pvt. Ltd.
                    <br />
                    info@da360.ai
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
