export const studentsRow1  = [
    { image: "/images/rating/video.jpg" },
    { image: "/images/rating/video1.jpg" },
    { image: "/images/rating/video2.jpg" },
    { image: "/images/rating/video3.jpg" },
    { image: "/images/rating/video4.jpg" },
    { image: "/images/rating/video5.jpg" },
    { image: "/images/rating/video6.jpg" },
    { image: "/images/rating/video7.jpg" },
    { image: "/images/rating/video8.jpg" },
    { image: "/images/rating/video9.jpg" },
    { image: "/images/rating/video10.jpg" },
    { image: "/images/rating/video11.jpg" },
    { image: "/images/rating/video3.jpg" },
    { image: "/images/rating/video9.jpg" },
    { image: "/images/rating/video3.jpg" },
    { image: "/images/rating/video4.jpg" },
    { image: "/images/rating/video5.jpg" },
    { image: "/images/rating/video6.jpg" },
    { image: "/images/rating/video7.jpg" },
];
  
export const studentsRow2  = [
    { image: "/images/rating/video.jpg" },
    { image: "/images/rating/video1.jpg" },
    { image: "/images/rating/video2.jpg" },
    { image: "/images/rating/video3.jpg" },
    { image: "/images/rating/video4.jpg" },
    { image: "/images/rating/video5.jpg" },
    { image: "/images/rating/video6.jpg" },
    { image: "/images/rating/video7.jpg" },
    { image: "/images/rating/video8.jpg" },
    { image: "/images/rating/video9.jpg" },
    { image: "/images/rating/video10.jpg" },
    { image: "/images/rating/video11.jpg" },
    { image: "/images/rating/video3.jpg" },
    { image: "/images/rating/video9.jpg" },
    { image: "/images/rating/video3.jpg" },
    { image: "/images/rating/video4.jpg" },
    { image: "/images/rating/video5.jpg" },
    { image: "/images/rating/video6.jpg" },
    { image: "/images/rating/video7.jpg" },
  ];
  
  