export const studentsRow1  = [
    { image: "/images/profiles/student1.png" },
    { image: "/images/profiles/student2.png" },
    { image: "/images/profiles/student3.png" },
    { image: "/images/profiles/student4.png" },
    { image: "/images/profiles/student5.png" },
    { image: "/images/profiles/student6.png" },
    { image: "/images/profiles/student7.png" },
    { image: "/images/profiles/student8.png" },
    { image: "/images/profiles/student9.png" },
    { image: "/images/profiles/student10.png" },
    { image: "/images/profiles/student11.png" },
    { image: "/images/profiles/student12.png" },
    { image: "/images/profiles/student13.png" },
    { image: "/images/profiles/student14.png" },
    { image: "/images/profiles/student15.png" },
    { image: "/images/profiles/student16.png" },
    { image: "/images/profiles/student17.png" },
    { image: "/images/profiles/student18.png" },
    { image: "/images/profiles/student19.png" },
    { image: "/images/profiles/student20.png" },
    { image: "/images/profiles/student21.png" },
];
  
export const studentsRow2  = [
    { image: "/images/profiles/student1.png" },
    { image: "/images/profiles/student2.png" },
    { image: "/images/profiles/student3.png" },
    { image: "/images/profiles/student4.png" },
    { image: "/images/profiles/student5.png" },
    { image: "/images/profiles/student6.png" },
    { image: "/images/profiles/student7.png" },
    { image: "/images/profiles/student8.png" },
    { image: "/images/profiles/student9.png" },
    { image: "/images/profiles/student10.png" },
    { image: "/images/profiles/student11.png" },
    { image: "/images/profiles/student12.png" },
    { image: "/images/profiles/student13.png" },
    { image: "/images/profiles/student14.png" },
    { image: "/images/profiles/student15.png" },
    { image: "/images/profiles/student16.png" },
    { image: "/images/profiles/student17.png" },
    { image: "/images/profiles/student18.png" },
    { image: "/images/profiles/student19.png" },
    { image: "/images/profiles/student20.png" },
    { image: "/images/profiles/student21.png" },
  ];
  
  