import Assesment from "@/components/Ui/svg/assesment";
import Assignment from "@/components/Ui/svg/assignment";
import CaseStudy from "@/components/Ui/svg/caseStudy";
import Live from "@/components/Ui/svg/live";
import type { CurriculumProps } from "@/types/curriculum";

export const curriculumData: CurriculumProps = {
  heading: "Latest Curriculum Reviewed by Industry Leaders",
  description:
    "Cutting-edge digital marketing syllabus—designed by Expert trainers and endorsed by top recruiters and domain experts.",
  learningMode: "Offline",
  batchTimings: [
    {
      label: "Classroom (Leadership)",
      slots: ["11:00 AM to 5:00 PM"],
    },
    {
      label: "",
      slots: [""],
    },
  ],
  modules: [
    {
      number: 1,
      title: "Digital Marketing 360°: From Basics to Mastery",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Introduction to Digital Marketing Ecosystem",
        "Principles & Foundations of Marketing",
        "Branding, Design Thinking & Business Fundamentals",
        "Owned, Earned & Paid Media Models",
        "Market Research & Audience Analysis",
        "Customer Journey Mapping & Persona Creation",
        "Goal-Setting Frameworks: Fame, Followers, Finance",
        "Evolution of AI in Digital Marketing",
        "Case Studies: Indian & Global Digital Leaders",
      ],
    },
    {
      number: 2,
      title: "AI-Driven Content & Leadership in Marketing",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Leadership Styles & Their Use in Digital Marketing",
        "AI in Market Research & Keyword Analysis",
        "Generative AI for Content Strategy",
        "Prompt Engineering for Marketing Content",
        "AI-Powered Keyword Research & Tools",
        "Crafting SEO-Friendly AI Blogs & Articles",
        "Measuring ROI from AI-Driven Campaigns",
        "Forecasting Trends with AI Insights",
        "Leadership Case Studies in Content Strategy",
      ],
    },
    {
      number: 3,
      title: "Digital Entrepreneurship & Web Presence Development",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Fundamentals of Digital Entrepreneurship",
        "WordPress Website Design: Setup & Tools",
        "UI/UX Design Principles & Elements",
        "Canva & Figma for Social Media Creatives",
        "Logo Designing with HuMint & Brandmark",
        "Creating Professional Email IDs & Domains",
        "Portfolio Creation & Multi-Page Websites",
        "Setting Up Online Stores (Shopify, WooCommerce)",
        "Website Launch & Optimization",
      ],
    },
    {
      number: 4,
      title: "Foundations of Social Content Creation & Personal Branding",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "The Rise of Social Content Creators in 2025",
        "Psychology of Influence & Community Building",
        "Selecting Your Niche & Identifying Target Audience",
        "Components of a Strong Personal Brand",
        "Storytelling Frameworks for Creators",
        "Crafting Your Creator Identity & Voice",
        "Case Studies: Global & Indian Creator Journeys",
        "Goal Setting: Followers, Fame, Finance & Impact",
      ],
    },
    {
      number: 5,
      title: "Content Strategy & Social Media Platforms Mastery",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Understanding Owned, Earned & Paid Media",
        "Instagram, YouTube, LinkedIn & TikTok Ecosystems",
        "Short-Form vs. Long-Form Content Strategy",
        "Content Calendar & Consistency Planning",
        "Researching Trends with AI Tools",
        "Audience Behavior & Engagement Psychology",
        "Monetization Readiness via Strategic Content Mix",
        "Case Studies of Viral Campaigns",
      ],
    },
    {
      number: 6,
      title: "Video Production Fundamentals",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Basics of Shooting: Camera Angles, Framing, Lighting",
        "Shooting with Smartphones vs. DSLR",
        "Studio Setup for Creators (Budget-Friendly)",
        "Audio Recording, Voiceovers & Sound Design",
        "Scriptwriting & Storyboarding Techniques",
        "Batch Recording & Workflow Planning",
        "Building a Video Production Workflow",
        "Tools: CapCut, InShot, Premiere Pro",
      ],
    },
    {
      number: 7,
      title: "Advanced Video Editing & Motion Graphics",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Professional Editing Techniques (Transitions, Cuts, Color Grading)",
        "AI Tools for Editing: Descript, Wisecut, Runway",
        "Adding Subtitles, Captions & Hooks",
        "Motion Graphics & Intro/Outro Branding",
        "Visual Consistency & Brand Kit Creation",
        "Canva & Adobe After Effects for Creators",
        "Creating Thumbnails & Click-Worthy Visuals",
        "Case Study: Editing Styles of Top Influencers",
      ],
    },
    {
      number: 8,
      title: "Instagram Growth & Influence Mastery",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Instagram SEO & Algorithm Insights",
        "Profile Optimization & All-Star Bio",
        "Mastering Reels: Hooks, Scripts & Transitions",
        "Carousel, Story & Live Content Best Practices",
        "Collaboration Strategies with Influencers & Brands",
        "Shadowban Prevention & Compliance",
        "Analytics Tools & Growth Hacks",
        "Case Study: Instagram Creator Success Stories",
      ],
    },
    {
      number: 9,
      title: "YouTube Channel Growth & Video Monetization",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "YouTube Channel Setup & Branding",
        "Niche Selection & SEO-Optimized Titles/Descriptions",
        "Creating Shorts vs. Long-Form Strategy",
        "Thumbnail & Hook Frameworks for Virality",
        "YouTube Partner Program & Monetization",
        "Community Tab & Playlist Optimization",
        "Advanced Analytics for Retention & CTR",
        "Case Study: Successful Indian YouTubers",
      ],
    },
    {
      number: 10,
      title: "LinkedIn & Thought Leadership for Creators",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Building LinkedIn All-Star Profiles",
        "Crafting Value-Driven Headlines & Summaries",
        "Content Buckets: Authority, Inspiration, Relatable",
        "Writing Viral Carousels with Canva",
        "Leveraging LinkedIn Events & Newsletters",
        "Growing a Professional Creator Network",
        "LinkedIn Ads for Creator Branding",
        "Case Study: Thought Leaders on LinkedIn",
      ],
    },
    {
      number: 11,
      title: "Influencer Marketing & Brand Collaborations",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Building a Media Kit & Creator Portfolio",
        "Pricing Models: Barter, Affiliate, Sponsorships",
        "Outreach to Brands & PR Agencies",
        "Influencer Platforms: Upfluence, Winkl, One Impression",
        "Crafting High-ROI Influencer Campaigns",
        "FTC Guidelines & Brand Safety Rules",
        "Negotiation & Contract Handling",
        "Case Studies of Influencer Collaborations",
      ],
    },
    {
      number: 12,
      title: "Meme Marketing & Social Virality",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Understanding Meme Culture & Trends",
        "Designing Shareable & Relatable Memes",
        "Viral Content Frameworks & Hooks",
        "Integrating Memes into Brand Campaigns",
        "UGC (User-Generated Content) Strategies",
        "Engagement Loops: Polls, Comments & Reposts",
        "Growth Challenges & Giveaways",
        "Measuring Meme Marketing ROI",
      ],
    },
    {
      number: 13,
      title: "Monetization & Revenue Diversification",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "YouTube: Ads, Super Chats, Memberships",
        "Instagram: Bonuses, Collab Posts & Subscriptions",
        "Affiliate Marketing for Creators",
        "Merchandising & Dropshipping",
        "Paid Webinars, Workshops & Courses",
        "Building Paid Communities (WhatsApp/Telegram)",
        "UGC Platforms for Creators",
        "Tracking Creator Taxes & Legalities",
      ],
    },
    {
      number: 14,
      title: "AI-Powered Tools for Content Creators",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "AI Scriptwriting Tools: ChatGPT, Jasper",
        "AI Video Tools: HeyGen, Pictory, Lumen5",
        "AI Voiceovers & Avatars for Content",
        "Trend Forecasting with AI Tools",
        "AI Analytics Tools for Social Media",
        "Automation Tools for Content Scheduling",
        "Using AI for Competitor Analysis",
        "ROI Measurement with AI Dashboards",
      ],
    },
    {
      number: 15,
      title: "Creator Leadership, Soft Skills & Personal Development",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "On-Camera Confidence & Presence",
        "Storytelling for Emotional Connection",
        "Handling Online Criticism & Trolls",
        "Negotiation Skills for Creator Deals",
        "Building Authority Through Speaking & Panels",
        "LinkedIn & Twitter for Thought Leadership",
        "Productivity & Burnout Management",
        "Collaboration with Other Creators",
      ],
    },
    {
      number: 16,
      title: "Digital Aesthetics & Advanced Video Engineering",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Branding & Identity Design for Creators",
        "Advanced Video Editing with After Effects",
        "Motion Graphics for Reels & Shorts",
        "Building Signature Video Styles",
        "Creating Engaging Brand Shoots",
        "Podcast Setup & Editing Basics",
        "Emerging Trends in Video Content",
        "Case Study: Netflix & Brand-Led Video Campaigns",
      ],
    },
    {
      number: 17,
      title: "Creator Growth, Analytics & Performance",
      badges: [
        { icon: <Live />, label: "10 Live Sessions" },
        { icon: <Assignment />, label: "2 Assignments" },
        { icon: <CaseStudy />, label: "1 Case Study" },
        { icon: <Assesment />, label: "2 Assessments" },
      ],
      topics: [
        "Advanced Analytics: Shield, VidIQ, TubeBuddy",
        "Content Repurposing Across Platforms",
        "Growth Loops & Subscriber Retention",
        "Paid Promotion Strategies",
        "Data-Driven Decision Making",
        "ROI Measurement for Content Creators",
        "Building High-Ticket Brand Positioning",
        "Scaling to a Personal Branding Agency",
      ],
    },
    {
      number: 18,
      title: "3-Month Agency Internship (Capstone)",
      badges: [
        { icon: <Live />, label: "12 Weeks of Hands-On Experience" },
        { icon: <Live />, label: "Live Client Campaigns" },
        { icon: <Live />, label: "Performance-Based Deliverables" },
        { icon: <Live />, label: "Final Capstone Project" },
      ],
      topics: [
        "Create 20 Viral Reels & Shorts",
        "2 High-Impact Brand Collaborations",
        "Full SEO & Social Media Audit for a Client",
        "Running Paid Ads (Meta & YouTube)",
        "Designing a Complete Content Calendar",
        "1000 Backlinks & 16 Blogs for Client Site",
        "Managing 2 Real Client Campaigns",
        "Delivering Analytics & ROI Reports",
        "Generating 100 Qualified Leads",
      ],
    },
  ],
};
