import Live from "@/components/Ui/svg/live";
import type { CurriculumProps } from "@/types/curriculum";

export const curriculumData: CurriculumProps = {
  heading: "Latest Curriculum Reviewed by Industry Leaders",
  description:
    "Cutting-edge digital marketing syllabus—designed by Expert trainers and endorsed by top recruiters and domain experts.",
  learningMode: "Offline",
  batchTimings: [
    {
      label: "Classroom (Leadership)",
      slots: ["11:00 AM to 5:00 PM"],
    },
    {
      label: "",
      slots: [""],
    },
  ],
  modules: [
    {
      number: 1,
      title: "Digital Marketing 360°: From Basics to Mastery",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "Marketing & Principles of Marketing",
        "Introduction to Digital Marketing",
        "Branding Designing & Business Fundamentals",
        "Owned, Earned & Paid Media",
        "Market Research & Analysis",
        "Customer Journey & Building Customer Persona",
        "Advanced Level Keyword Research",
        "All Keyword Research Tools",
        "Importance of AI in Digital Marketing",
        "AI Content Generation",
        "Leadership Styles",
        "Leadership use in Digital Marketing",
      ],
    },
    {
      number: 2,
      title: "Digital Entrepreneurship & Footprint",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "WordPress Website Designing - Personal Website Building",
        "Design Principles and Elements",
        "Graphic Design Tools",
        "UI/UX Design",
        "Canva - Poster & Social Media Creative Designing",
        "Logo Designing Basics - HuMint & Brandmark",
        "Domain & Hosting",
        "UI UX Fundamentals",
        "Creating Professional Email IDs",
        "Introduction to WordPress",
        "WordPress Tools & Themes",
        "Theme Selection",
        "Designing Multiple Pages Basics",
        "Portfolio Creation in Website",
        "Launch of Website",
        "E-commerce Basics and Business Models",
        "Setting up an Online Store (Shopify, WooCommerce, etc.)",
      ],
    },
    {
      number: 3,
      title: "Next-Gen SEO & AI-Driven Content Strategy",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "On-Page SEO",
        "Technical SEO and Schema Algorithm Validation",
        "Mobile SEO",
        "E-A-T",
        "20+ Backlinks Creation Methods",
        "Google Webmaster Tools",
        "Bing Webmaster Tools",
        "Conversion Rate Optimization",
        "App Store SEO",
        "Strategies for International SEO",
        "Local SEO and GMB",
        "Apple Maps Optimization",
        "SEO Reporting",
        "SEO Forecasting",
        "Content Strategy Planning",
        "Proof of Concept in SEO",
        "AI Powered Content Generation",
        "SEO Audit and Tools",
        "Advanced SEO Optimization",
        "Optimizing AMP and Mobile Apps for PWAs",
        "How to use Generative AI + ChatGPT for SEO",
        "Google SERP and Ranking Fluctuations",
        "Advanced Competitor Analysis and Strategy",
        "Practical AI for SEO examples",
        "SEO Forecasting and Predictions",
        "AI Powered SEO Writing",
        "Latest Google Algorithm Updates",
      ],
    },
    {
      number: 4,
      title: "Social Media Intelligence & Brand Impact",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "Social Media Marketing & Personal Branding",
        "Social Business Profile Creations",
        "Facebook & Instagram SEO",
        "LinkedIn & YouTube SEO",
        "LinkedIn All Star Profile & Personal Branding",
        "Advanced Social Media Calendar Planning",
        "Social Media Competitor Analysis",
        "Social Media Brand & Reputation Management",
        "Social Media Strategy & Planning",
        "Meta Ads & Business Manager Creation",
        "Lead Generation & Traffic Campaigns",
        "LinkedIn Ads",
        "Quora Ads",
      ],
    },
    {
      number: 5,
      title: "Strategic Influence & Social Virality",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "Understanding Meme Culture",
        "Creating Effective Memes",
        "Meme Marketing Strategies",
        "Identifying Influencers",
        "Influencer Marketing Campaign Planning",
        "Collaboration with Influencers",
        "Measuring Influencer Marketing ROI",
        "Legal and Ethical Considerations of Influencer Marketing",
        "Micro-Influencer Marketing",
        "User-Generated Content",
      ],
    },
    {
      number: 6,
      title: "Advanced PPC & High-Performance Ad Strategy",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "Google Search Ads",
        "Google Display Ads",
        "Google Shopping Ads",
        "YouTube Marketing",
        "App Marketing",
        "Lead Generation Ads",
        "Landing Page Creation",
      ],
    },
    {
      number: 7,
      title: "ROI-Driven Growth & Performance Ad Optimization",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "Conversion Rate Optimization",
        "Goals Setting + A/B Funnels + 4 Pillars of Performance Marketing",
        "1st Party Audience Creation, Definition & Evaluation",
        "In-depth study of evaluating advertisements in advertising",
        "Ad Copy with research and the framework and using AI",
        "Principles of CTR funnels and designing the direction of your ads",
        "Running A/B testing on Google Ads and Facebook Ads for improved outcomes",
        "Remarketing campaigns setup on Google Ads and Facebook Ads",
        "Dynamic Campaigns",
        "Advanced Audience Selection, Catalog & Tracking",
        "Measuring ROI of ads",
        "Advanced live examples for product and service businesses",
      ],
    },
    {
      number: 8,
      title: "Media Influence & Automated Ad Buying",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "Media Planning Fundamentals",
        "Media Channels & Negotiation",
        "Media Buying",
        "Media Planning & Negotiation",
        "Media Planning and Digital Tools",
        "Programmatic Media Buying",
        "Real-Time Bidding (RTB)",
        "Demand-Side Platforms (DSPs)",
        "Supply-Side Platforms (SSPs)",
        "Data-Driven Attribution",
        "Performance Media Optimization",
      ],
    },
    {
      number: 9,
      title: "Advanced Digital Analytics & Marketing Data Science",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "Understanding Google Analytics",
        "Setting Up Google Analytics",
        "Tracking Website Traffic",
        "User Behavior Analytics",
        "Goal Tracking and Conversion Funnels",
        "E-commerce Tracking",
        "Audience Demographics and Interests",
        "Data Studio for Data Visualization",
        "Customizing Dashboards and Reports",
        "Data-Driven Decision Making",
      ],
    },
    {
      number: 10,
      title: "Strategic Brand Positioning & Digital PR Mastery",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "Brand Identity and Positioning",
        "Brand Messaging and Storytelling",
        "Brand Guidelines and Standards",
        "Crisis Communication and Management",
        "Media Relations and Outreach",
        "Public Relations Strategies",
        "Social Media PR",
        "Influencer PR",
        "Brand Partnerships and Collaborations",
        "Measuring PR Effectiveness",
      ],
    },
    {
      number: 11,
      title: "Business Growth & Digital Marketing Agency Mastery",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "Freelancing Basics and Platforms",
        "Building a Strong Freelancer Profile",
        "Client Acquisition Strategies",
        "Time Management and Project Prioritization",
        "Financial Management and Taxes",
        "Legal and Ethical Considerations",
        "Starting a Digital Marketing Agency",
        "Business Planning and Strategy",
        "Team Building and Management",
        "Agency Growth",
      ],
    },
    {
      number: 12,
      title: "Digital Strategy & High-Impact Marketing Presentations",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "Understanding Client Needs and Goals",
        "Developing Digital Marketing Strategies",
        "Creating Detailed Marketing Plans",
        "Budget Planning and Resource Allocation",
        "Project Planning and Timeline Management",
        "Client Communication and Relationship Building",
        "Presentation Skills and Techniques",
        "Creating Effective Marketing Presentations",
        "Data-Driven Insights and Recommendations",
      ],
    },
    {
      number: 13,
      title: "AI-Powered Ecommerce & Data-Driven Sales",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "Introduction to E-Commerce",
        "E-Commerce Business Models",
        "Choosing the Right E-Commerce Platform",
        "On-Page SEO for E-Commerce",
        "Off-Page SEO for E-Commerce",
        "Google Ads for E-Commerce",
        "Google Analytics for E-Commerce",
        "Google Ads Remarketing for E-Commerce",
        "Google Analytics E-Commerce Tracking",
        "Data Analysis & Reporting",
        "AI Powered E-Commerce Trends",
        "Customer Retention Strategies",
        "Order Fulfillment Options",
        "Shipping and Delivery",
        "Payment Gateway Integrations",
        "Analyzing E-Commerce Businesses",
        "Shopify and its Ecosystem",
        "Connecting Shopify with Facebook and Google",
      ],
    },
    {
      number: 14,
      title: "Martech, Automation & Data-Driven Marketing Execution",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "What is Project & Project Management?",
        "Managing Projects & Using Automations",
        "Improving Productivity With Automations",
        "Building ICP For B2B Businesses",
        "Data Led Marketing & ABM Strategies",
        "Account Based Marketing - ABM",
        "Tools to Automate Outreach",
        "All About CRM",
        "Building Automations to Nurture Leads",
        "Key Metrics & Reporting Methods",
        "Email Marketing",
        "Omnichannel & Drip Email Automations",
        "Understanding Zapier ecosystem",
        "Omnichannel Live Chat & Chat Bot",
        "What is Chatbot Workflow?",
        "Whatsapp & SMS Marketing",
        "Affiliate Marketing",
        "Google Ads Smart Mode",
        "Building GTM (Go To Market) Strategies",
        "Mastering PLG (Product Led Growth)",
      ],
    },
    {
      number: 15,
      title: "Digital Aesthetics & Video Engineering",
      badges: [
        { icon: <Live />, label: "8 Live Sessions" },
        { icon: <Live />, label: "3 Assignments" },
        { icon: <Live />, label: "2 Case Studies" },
        { icon: <Live />, label: "1 Assessment" },
      ],
      topics: [
        "Branding and Identity Design",
        "Video Production Fundamentals",
        "Video Editing Software",
        "Motion Graphics and Animation",
        "Video Marketing and Storytelling",
        "Video Production Workflow and Best Practices",
        "Emerging Trends in Design and Video",
      ],
    },
  ],
};
